INSERT INTO categories (name) VALUES ('Micro');
INSERT INTO categories (name) VALUES ('Sedan');
INSERT INTO categories (name) VALUES ('Coupe');
INSERT INTO categories (name) VALUES ('Pickup');
INSERT INTO categories (name) VALUES ('Sport car');
INSERT INTO categories (name) VALUES ('SUV');
INSERT INTO categories (name) VALUES ('Minivan');
INSERT INTO categories (name) VALUES ('Crossover');
INSERT INTO categories (name) VALUES ('Hatchback');
INSERT INTO categories (name) VALUES ('Muscle car');
INSERT INTO categories (name) VALUES ('Minibus');
INSERT INTO categories (name) VALUES ('Campervan');
